name: Django CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, "3.10", "3.11"] # Test against relevant Python versions

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # - name: Run Tests (Example - uncomment and adapt when tests are written)
    #   env: # Set environment variables for testing if needed
    #     SECRET_KEY: ${{ secrets.DJANGO_TEST_SECRET_KEY }} # Store a dummy secret in GitHub secrets for tests
    #     DB_ENGINE: django.db.backends.sqlite3 # Use SQLite for CI tests for simplicity
    #     DB_NAME: test_db.sqlite3
    #   run: |
    #     python manage.py test apps.users # Run tests for a specific app
