# .github/workflows/django-ci.yml
name: Django CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test: # Renamed job for clarity
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"] # Focus on one primary version for CI speed, or keep all [3.9, "3.10", "3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # Cache dependencies for faster runs

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y default-libmysqlclient-dev gcc # Even for SQLite, good to keep if needed

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django Tests
      env:
        # --- Essential ---
        SECRET_KEY: ${{ secrets.DJANGO_TEST_SECRET_KEY }} # ADD THIS SECRET in GitHub > Settings > Secrets > Actions
        DJANGO_DEBUG: "True" # Usually True for tests
        # --- Use SQLite for CI Tests ---
        DB_ENGINE: "django.db.backends.sqlite3"
        DB_NAME: ":memory:" # Use in-memory SQLite for max speed
        # --- Dummy variables to prevent settings errors ---
        DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
        STRIPE_SECRET_KEY: "dummy_stripe_key"
        AI_NLP_TUTOR_SERVICE_URL: "http://dummy.url"
        AI_TTS_SERVICE_URL: "http://dummy.url"
        AI_TTV_SERVICE_URL: "http://dummy.url"
        AI_PROJECT_GENERATOR_SERVICE_URL: "http://dummy.url"
        AI_PROJECT_ASSESSMENT_SERVICE_URL: "http://dummy.url"
        AI_SERVICE_API_KEY: "dummy_ai_key"
        # Add any other required environment variables here with dummy values

      run: |
        python manage.py test # Run ALL tests in your project
